# Generated by Django 4.0.1 on 2022-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_seller_address_seller_city_seller_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller-profile-picture'),
        ),
    ]
