# Generated by Django 4.0.1 on 2022-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('is_success', models.BooleanField(default=False, help_text='If user successfully went through the process')),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
