# Generated by Django 4.0.1 on 2022-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_forgotpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpassword',
            old_name='requested_on',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
