# Generated by Django 4.0.1 on 2022-09-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_requested_on_forgotpassword_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpassword',
            old_name='slug',
            new_name='otp',
        ),
    ]
