# Generated by Django 4.0.1 on 2022-09-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_slug_forgotpassword_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForgotPassword',
            new_name='ForgotPasswordOTP',
        ),
    ]
