# Generated by Django 4.0.1 on 2022-09-11 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_is_success_forgotpasswordotp_is_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordotp',
            name='expired',
        ),
        migrations.AddField(
            model_name='forgotpasswordotp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 10, 54, 25, 119874), help_text='Expires after 5 minutes'),
        ),
    ]
