# Generated by Django 4.0.1 on 2022-09-11 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_forgotpasswordotp_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 10, 54, 33, 554285), help_text='Expires after 5 minutes'),
        ),
    ]
