# Generated by Django 4.0.1 on 2022-09-11 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_forgotpasswordotp_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordotp',
            name='is_used',
            field=models.BooleanField(default=False, help_text='If token has been used'),
        ),
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 11, 23, 50, 476665), help_text='Expires after 5 minutes'),
        ),
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='If token was sent successfully'),
        ),
    ]
