# Generated by Django 4.0.1 on 2022-09-19 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_forgotpasswordotp_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 14, 21, 43, 327453, tzinfo=utc), help_text='Expires after 5 minutes'),
        ),
    ]
