# Generated by Django 4.0.1 on 2022-09-20 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_forgotpasswordotp_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 14, 20, 2, 662598, tzinfo=utc), help_text='Expires after 5 minutes'),
        ),
    ]
