# Generated by Django 4.0.1 on 2022-09-26 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_forgotpasswordotp_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 37, 53, 397815, tzinfo=utc), help_text='Expires after 5 minutes'),
        ),
    ]
