# Generated by Django 4.0.1 on 2022-09-26 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_profile_wallet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordotp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 12, 10, 40, 457060, tzinfo=utc), help_text='Expires after 5 minutes'),
        ),
    ]
