# Generated by Django 4.0.1 on 2022-01-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='brands',
            field=models.ManyToManyField(default=None, related_name='brands', to='store.Brand'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='store.productdetail'),
        ),
        migrations.AlterField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='merchant.seller'),
        ),
    ]
