# Generated by Django 4.0.1 on 2022-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productcategory_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
