# Generated by Django 4.0.1 on 2022-02-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='brands',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='brands', to='store.Brand'),
        ),
    ]
