# Generated by Django 4.0.1 on 2022-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
