# Generated by Django 4.0.1 on 2022-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_count',
            field=models.IntegerField(default=0),
        ),
    ]
