# Generated by Django 4.0.1 on 2022-09-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_selling_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_count',
            new_name='sale_count',
        ),
    ]
