# Generated by Django 4.0.1 on 2022-09-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_selling_count_product_sale_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='g.png', upload_to='product-images'),
        ),
    ]
