# Generated by Django 4.0.1 on 2022-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_alter_seller_status'),
        ('store', '0013_alter_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price_promo', models.BooleanField(default=False, help_text='Enter price if this is selected')),
                ('merchant_promo', models.BooleanField(default=False, help_text='Select merchant(s) if this is selected')),
                ('category_promo', models.BooleanField(default=False, help_text='Select category(s) if this is selected')),
                ('sub_category_promo', models.BooleanField(default=False, help_text='Select sub_category(s) if this is selected')),
                ('product_promo', models.BooleanField(default=False, help_text='Select product(s) if this is selected')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], default='fixed', max_length=50)),
                ('discount', models.IntegerField(blank=True, default=0, help_text='Discount value, 1 means 1% if discount type is percentage, 1000 means fixed discount of 1000 if discount type is fixed', null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promo banners')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, to='store.ProductCategory')),
                ('merchant', models.ManyToManyField(blank=True, to='merchant.Seller')),
                ('product', models.ManyToManyField(blank=True, to='store.Product')),
                ('sub_category', models.ManyToManyField(blank=True, related_name='sub_category', to='store.ProductCategory')),
            ],
        ),
    ]
