# Generated by Django 4.0.1 on 2022-09-20 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_uid',
            field=models.UUIDField(default=uuid.UUID('f2a6a017-8616-40f6-bc55-083cc70b4a23'), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
