# Generated by Django 4.0.1 on 2022-09-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cart_cart_uid_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_uid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
