# Generated by Django 4.0.1 on 2022-09-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_cart_cart_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='status',
        ),
    ]
