# Generated by Django 4.0.1 on 2022-09-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_alter_seller_status'),
        ('store', '0017_remove_cartproduct_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Promo',
        ),
    ]
