# Generated by Django 4.0.1 on 2022-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_deals_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='promo_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('deal', 'Deal'), ('promo', 'Promo')], default='promo', max_length=50),
        ),
    ]
