# Generated by Django 4.1.3 on 2023-02-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorblock',
            name='allow_blurry_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validatorblock',
            name='allow_content_type_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validatorblock',
            name='allow_dimension_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validatorblock',
            name='allow_extension_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validatorblock',
            name='allow_number_of_image_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validatorblock',
            name='allow_size_check',
            field=models.BooleanField(default=False),
        ),
    ]
