# Generated by Django 4.1.3 on 2022-12-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorblock',
            name='content_type',
            field=models.ManyToManyField(help_text="What ever content type that has been selected by the client will be allowed for the Image Processing of this Validator Block. E.g {'jpeg': 'image/jpeg'}, it means images with content type of jpeg will be acceptable.", to='management.applicationcontenttype'),
        ),
    ]
