# Generated by Django 4.1.3 on 2023-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_validatorblock_numb_of_images_per_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatorblock',
            name='image_dimension_threshold',
        ),
        migrations.AddField(
            model_name='validatorblock',
            name='image_height_dimension_threshold',
            field=models.PositiveSmallIntegerField(default=0, help_text='image height dimension treshold will be used to validate both height.'),
        ),
        migrations.AddField(
            model_name='validatorblock',
            name='image_width_dimension_threshold',
            field=models.PositiveSmallIntegerField(default=0, help_text='image width dimension treshold will be used to validate both width.'),
        ),
        migrations.AlterField(
            model_name='validatorblock',
            name='numb_of_images_per_process',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
