# Generated by Django 4.1.3 on 2023-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(help_text='List of content-type available on the platform. e.g image/png', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_name', models.CharField(help_text='List of extension available on the platform. e.g .png', max_length=10)),
            ],
        ),
    ]
